version: '3.9'

services:
  frontend:
    image: mapan694/font-app:latest
    container_name: font-app
    ports:
      - '9000:9000'
    environment:
      VITE_SERVER_BASEURL: 'http://backend:8000'
      VITE_UPLOAD_BASEURL: 'https://ukw0y1.laf.run/upload'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: mapan694/backend-app:latest
    container_name: backend-app
    ports:
      - '8000:8000'
    environment:
      DB_HOST: '192.168.1.100'
      DB_PORT: '5432'
      DB_USER: 'myuser'
      DB_PASSWORD: 'mypass'
      REDIS_HOST: '192.168.1.101'
      REDIS_PORT: '6379'
      # 可继续添加你已有的环境变量
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
